### ISSUE TITLE
HANDS2019

### ISSUE THREAD

**Issue by pineapple-king** [iscas3dv/handpose-virtualview#1]
Can you provide the data preprocessing code for the hands2019 dataset?

**Comment by ME495** [comment]
Sorry, we don't want to disclose the code related to the HANDS2019 dataset. I recommend you to refer to this code [https://github.com/wozhangzhaohui/HandAugment/blob/master/data/hands19task1.py](https://github.com/wozhangzhaohui/HandAugment/blob/master/data/hands19task1.py)

**Comment by ME495** [comment]
Thanks for your interest in our work. I have provided the data processing code for the hands2019 dataset. Hope that can help. Due to some issues, I am not permitted to release the training and testing code on this dataset now.
