### ISSUE TITLE
Unable to load and train the model

### ISSUE THREAD

**Issue by harish-udhay** [iscas3dv/handpose-virtualview#3]
Hello,

I'm a student currently pursing my M.S in Computer Science **(Email: harish.udhayakumar@rutgers.edu)**. The project posting is impressive. I'm currently trying to replicate this repo, however, I'm facing a couple of issues in loading the existing model. I'm not sure how to train a model from scratch too. 
I followed the steps posted in github profile (until placing the dataset and pointing the config(icvl.json) to the dataset directory. However, I'm not able to run the code using any existing model (from the  link provided).
Errors that I got when I tried loading the model - 

**1)** 
Command: python3 train_a2j.py --config config/icvl/eval_25select15.yaml --phase eval
**Error:** UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 0: invalid start byte

**2)**   
Command: python3 train_a2j.py --config config/icvl/eval_25select9_light.yaml --phase eval
File "train_a2j.py", line 505, in <module>
    assert (key in keys)
AssertionError

**3)**
Command: python3 train_a2j.py --config config/icvl/eval_25select9.yaml --phase eval
**Error:**
  File "train_a2j.py", line 520, in <module>
    processor = Processor(args)
  File "train_a2j.py", line 103, in __init__
    self.model, self.loss_calc = self.load_model()
  File "train_a2j.py", line 175, in load_model
    self.checkpoint = torch.load(self.pre_model_name)
  File "/common/users/hu33/anaconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/common/users/hu33/anaconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK

The errors remained the same when I changed the phase to 'train'.  It will be really helpful if you could guide me through it.

**Comment by ME495** [comment]
Thanks for your interest in our work. This error is caused by models being damaged during network transmission. We have uploaded new models and updated the README, please download and try again.

**Comment by harish-udhay** [comment]
Sure Thank you. In train_a2j.py (Line 234) could you explain how the output looks like? What is the physical meaning of output?
![image](https://user-images.githubusercontent.com/70934463/173285040-dc454f34-59d6-4c42-91cf-592f0e775932.png).

**Comment by ME495** [comment]
`crop_expand` represents the depth images rendered by views.

`anchor_joints_2d_crop` represents the predicted 2D joint coordinates only based on the anchor, `regression_joints_2d_crop` represents the predicted final 2D joint coordinates and `depth_value_norm` is the predicted joint normalized depth value, these are defined in `A2J`. `classification`, `regression` and `depthregression` are also defined in `A2J`.

`joints_3d_pred` is the 3D joint coordinates predicted by views.

`view_trans` represents the rotation transformation matrix of views.

`joint_3d_fused` represents the 3D joints that are fused by averaging the predicted 3D joints from views.

`conf` represents the view confidence.

`joint_3d_conf ` represents the 3D joints that are fused by weighted averaging the predicted 3D joints from views (view confidence as the weight).
