### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by tym7777** [iscas3dv/handpose-virtualview#5]
您好，我现在想尝试复现这篇论文，有一下两个问题：
1.我看到ops/cuda/depth_to_point_cloud_mask_cuda中的深度图和点云的相互转换是用cuda实现的，而我感觉这个操作就是把深度图中的手部像素点resize一下就是数据组织形式的改变，感觉没有很大的计算量，想问一下不直接用python写而是用c++实现的原因是什么？
2.请问我如果想自己训练这个网络需要什么样的GPU配置？
个人水平有限，希望能得到您的解答。

**Comment by tym7777** [comment]
Hello, I now want to try to reproduce this paper, I have the following questions:
I see that the mutual conversion between the depth map and the point cloud in ops/cuda/depth_to_point_cloud_mask_cuda is implemented with cuda, and I feel that this operation is to reshape the hand pixels in the depth map, which is a change in the form of data organization. I don't feel that there is a large amount of calculation. I would like to ask what is the reason why it is not written directly in python but implemented in c++?
Personal level is limited, I hope to get your answer.

**Comment by ME495** [comment]
问题1：
你说的对，用numpy可以很好地实现这个功能，并且像素点的数量很少，用cuda实现快不了多少。
问题2：
一张显存12G的显卡应该够了。

Question 1:
You're right, using numpy can achieve this function very well, and the number of pixels is very small, which is not much faster using cuda.
Question 2:
A GPU with 12GB memory should be enough.
