### ISSUE TITLE
How to do inference on real data？

### ISSUE THREAD

**Issue by laserwave** [iscas3dv/handpose-virtualview#7]
Hi，

I am confused how we can do inference on real data with the released pretrain models. 

In the eval or inference function in view_select_a2j.py, it requires the 3d joints to do depth image cropping. 

I can't understand this. How to get the 3d joints output with only depth image input?

**Comment by leekyungmoon** [comment]
@laserwave , Did you solve the issue? If so, can you tell me the way of doing inference on real data please?
