### ISSUE TITLE
如何对Azure Kinect DK拍摄的视频使用该算法？

### ISSUE THREAD

**Issue by cstg-liuziyu** [iscas3dv/handpose-virtualview#8]
在项目网页上看到了你们的实践，但我自己并没有办法达到那样好的效果，想问一下实际使用的思路是怎么样的？

**Comment by ME495** [comment]
对于Azure Kinect DK相机拍摄的RGBD图像，可以使用如下流程制作demo：
1. 使用人手检测模型从彩色图像中检测出人手边界框
2. 利用人手边界框，使用代码中的数据处理方法从深度图像中crop出人手深度图像
3. 将处理后的深度图像输入姿态估计模型

实际的效果取决于你的训练数据，我一般使用在NYU数据集训练的模型，但是对于NYU数据集中没有出现过的手势效果会很差

**Comment by cstg-liuziyu** [comment]
感谢您的回答
